# Generated by Django 5.2 on 2025-05-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IostatMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('disk', models.CharField(max_length=50)),
                ('tps', models.FloatField()),
                ('kb_read', models.FloatField()),
                ('kb_wrtn', models.FloatField()),
                ('service_time', models.FloatField()),
            ],
            options={
                'db_table': 'iostat_metrics',
            },
        ),
        migrations.CreateModel(
            name='NetstatMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('interface', models.CharField(max_length=50)),
                ('ipkts', models.IntegerField()),
                ('ierrs', models.IntegerField()),
                ('opkts', models.IntegerField()),
                ('oerrs', models.IntegerField()),
                ('coll', models.IntegerField()),
            ],
            options={
                'db_table': 'netstat_metrics',
            },
        ),
        migrations.CreateModel(
            name='ProcessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pid', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('cpu', models.FloatField()),
                ('mem', models.FloatField()),
                ('command', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'process_metrics',
            },
        ),
        migrations.CreateModel(
            name='VmstatMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('r', models.IntegerField()),
                ('b', models.IntegerField()),
                ('avm', models.IntegerField()),
                ('fre', models.IntegerField()),
                ('pi', models.IntegerField()),
                ('po', models.IntegerField()),
                ('fr', models.IntegerField()),
                ('interface_in', models.IntegerField(db_column='in')),
                ('cs', models.IntegerField()),
                ('us', models.FloatField()),
                ('sy', models.FloatField()),
                ('idle', models.FloatField()),
            ],
            options={
                'db_table': 'vmstat_metrics',
            },
        ),
    ]
