# Generated by Django 5.2 on 2025-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oracledatabase',
            name='sid',
            field=models.CharField(default='1521', help_text='Oracle SID (System Identifier)', max_length=100),
        ),
    ]
