# Generated by Django 5.2 on 2025-07-21 15:11

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iostatmetric',
            old_name='kb_read',
            new_name='kb_read_rate',
        ),
        migrations.RenameField(
            model_name='iostatmetric',
            old_name='kb_wrtn',
            new_name='kb_wrtn_rate',
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_key_path',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Path to SSH private key(encrypted)', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='ssh_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='SSH password (encrypted)', null=True),
        ),
    ]
