# Generated by Django 5.2 on 2025-08-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oracledatabase',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='oracletable',
            options={'ordering': ['id']},
        ),
    ]
