# Generated by Django 5.2 on 2025-05-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netstatmetric',
            old_name='coll',
            new_name='time',
        ),
    ]
