# Generated by Django 5.2 on 2025-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_rename_coll_netstatmetric_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iostatmetric',
            index=models.Index(fields=['timestamp'], name='iostat_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='netstatmetric',
            index=models.Index(fields=['timestamp'], name='netstat_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='netstatmetric',
            index=models.Index(fields=['interface'], name='netstat_interface_idx'),
        ),
        migrations.AddIndex(
            model_name='processmetric',
            index=models.Index(fields=['timestamp'], name='process_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='vmstatmetric',
            index=models.Index(fields=['timestamp'], name='vmstat_timestamp_idx'),
        ),
    ]
