# Generated by Django 5.2 on 2025-07-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_rename_kb_read_iostatmetric_kb_read_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iostatmetric',
            name='kb_read',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='iostatmetric',
            name='kb_wrtn',
            field=models.FloatField(default=0.0),
        ),
    ]
