# Generated by Django 5.2 on 2025-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_iostatmetric_kb_read_iostatmetric_kb_wrtn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netstatmetric',
            name='time',
            field=models.BigIntegerField(default=0, help_text='Timestamp'),
        ),
    ]
