# Generated by Django 5.2 on 2025-06-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_iostatmetric_iostat_timestamp_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netstatmetric',
            name='ipkts_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netstatmetric',
            name='opkts_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
