# Generated by Django 5.2 on 2025-08-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_rename_oracle_table'),
    ]

    operations = [
                migrations.AlterModelTable(
            name='oracledatabase',
            table='oracle_databases',
        ),
    ]
