# Generated by Django 5.2 on 2025-06-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_netstatmetric_ipkts_rate_netstatmetric_opkts_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='netstatmetric',
            name='ierrs_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='netstatmetric',
            name='oerrs_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
