# Generated by Django 5.2 on 2025-07-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_netstatmetric_ierrs_rate_netstatmetric_oerrs_rate'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='processmetric',
            name='process_timestamp_idx',
        ),
        migrations.AddIndex(
            model_name='processmetric',
            index=models.Index(fields=['timestamp', 'pid'], name='process_met_timesta_502c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='processmetric',
            index=models.Index(fields=['pid', 'timestamp'], name='process_met_pid_73984d_idx'),
        ),
    ]
