# Generated by Django 5.2 on 2025-06-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('is_anomaly', models.BooleanField()),
                ('anomaly_score', models.FloatField()),
                ('metric_values', models.JSONField()),
            ],
            options={
                'db_table': 'anomaly_detection',
                'indexes': [models.Index(fields=['timestamp'], name='anomaly_det_timesta_3f8d0b_idx'), models.Index(fields=['is_anomaly'], name='anomaly_det_is_anom_48cde9_idx')],
            },
        ),
    ]
