# Generated by Django 5.2 on 2025-06-05 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalydetectionresult',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='anomalydetectionresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='anomalydetectionresult',
            index=models.Index(fields=['created_at'], name='anomaly_det_created_1d1008_idx'),
        ),
    ]
